// client/NextJS/inv-mgmt/app/pages/components/Modal/Alert/Alert.tsx
'use client'

import {useEffect}  from 'react';

export interface AlertProps {
    dialogInfo: {};
    showModal: boolean;
    setShowModal: Function;
}

export default function Alert({dialogInfo,showModal,setShowModal}) {
    // each dialog MUST have a unique id
    let dialogId : string = Math.random().toString(36).replace('0.','alert.');
    console.log("*** dialog id " + dialogId);
    useEffect( () => {
        if (showModal) {
            showDialog();
        }
        else {
            closeDialog();
        }
     }, [showModal]);

    function closeDialog() {
        document.getElementById(dialogId)?.close()
    }
    
    function showDialog() {
        document.getElementById(dialogId)?.showModal();
    }

    return (
        <dialog id={dialogId}>
            <div style={{margin: "20px"}}>
                <div className="dialogTitle">{dialogInfo.title}</div>
                {dialogInfo.messages?.map((msg,idx) => (
                            <p key={idx}>{msg}</p>
                        ))}
                <button className="normalButton" onClick={() => setShowModal(false)}>Continue</button>
            </div>
        </dialog>
    );
}

// client/Vue/inv-mgmt/src/components/dialogs/Alert.vue
<script setup>
    const props = defineProps(['dialogInfo'])
    
    let dialogId = Math.random().toString(36).replace('0.','alert.');

    function closeDialog() {
        document.getElementById(dialogId)?.close();
    }
    
    function showDialog() {
        document.getElementById(dialogId)?.showModal();
    }

    // this exposes the show value to the outside so it can be set to true to show the dialog
    defineExpose({
        showDialog
    })

</script>

<template>
    <dialog :id="dialogId">
        <div style="margin: 10px">
            <div class="dialogTitle">{{props.dialogInfo.title}}</div>
            <p>
                <div v-for="msg in props.dialogInfo.messages">
                    {{ msg }}
                </div>
            </p>
            <button class="normalButton dialogButton" @click="closeDialog">Continue</button>
        </div>
        </dialog>
</template>

<style scoped src="./dialogs.css">

</style>
