// client/NextJS/inv-mgmt/app/pages/components/Modal/Confirm/Confirm.tsx
'use client'

import {useState, useEffect}  from 'react';

export interface ConfirmProps {
    dialogInfo: {};
    showModal: boolean;
    setShowModal: Function;
    yesHandler: Function|null;
    caller: Function|null;
}

export default function Confirm({dialogInfo,showModal,setShowModal}) {
    // each dialog MUST have a unique id
    let dialogId : string = Math.random().toString(36).replace('0.','alert.');
    console.log("*** dialog id " + dialogId);

    useEffect( () => {
        if (showModal) {
            showDialog();
        }
        else {
            closeDialog();
        }
     }, [showModal]);

     function closeDialog() {
        document.getElementById(dialogId)?.close()
    }
    
    function showDialog() {
        document.getElementById(dialogId)?.showModal();
    }

    function doYes() {
        setShowModal(false);
        if (dialogInfo.caller && dialogInfo.yesHandler) {
            dialogInfo.yesHandler.call(dialogInfo.caller);
        }
    }

    return (
        <dialog id={dialogId}>
            <div style={{margin: "20px"}}>
                <div className="dialogTitle">{dialogInfo.title}</div>
                {dialogInfo.messages?.map((msg,idx) => (
                            <p key={idx}>{msg}</p>
                        ))}
                <p>
                    <button className="normalButton" onClick={() => setShowModal(false)}>No</button>
                    <span style={{margin: "0px 20px 0px 20px"}}>&nbsp;</span>
                    <button className="normalButton" onClick={() => doYes()}>Yes</button>
                </p>
            </div>
        </dialog>
    );
}

// client/Vue/inv-mgmt/src/components/dialogs/Confirm.vue
<script setup>
    const props = defineProps(['dialogInfo'])
    
    let dialogId = Math.random().toString(36).replace('0.','alert.');

    function closeDialog() {
        document.getElementById(dialogId)?.close();
    }
    
    function showDialog() {
        document.getElementById(dialogId)?.showModal();
    }

    function doYes() {
        closeDialog();
        // because the "caller" is a component, not an object instance (ie, there is no "this"), 
        // we can call the handler directly
        if (props.dialogInfo.yesHandler) {
            props.dialogInfo.yesHandler();
        }
    }

    // this exposes the show value to the outside so it can be set to true to show the dialog
    defineExpose({
        showDialog
    })

</script>

<template>
    <dialog :id="dialogId">
        <div style="margin: 10px">
            <div className="dialogTitle">{{props.dialogInfo.title}}</div>
            <p>
                <div v-for="msg in props.dialogInfo.messages">
                    {{ msg }}
                </div>
            </p>
            <button class="normalButton dialogButton" @click="closeDialog">No</button>
            <span class="spacerLarge">&nbsp;</span>
            <button class="normalButton dialogButton" @click="doYes">Yes</button>
        </div>
        </dialog>
</template>

<style scoped src="./dialogs.css">

</style>
