// client/Vue/inv-mgmt/src/components/PickList/PickList.vue
<script setup>
import { ref, watch } from 'vue'

import PickListRequest from './PickListRequest.vue';
import PickListResult from './PickListResult.vue';

const pickData = ref({}),
      showMode = ref({value: 'request'})

watch(pickData, (newValue, prevValue) => {
    console.log("*** pick data changed");
    console.log(newValue);
    console.log(pickData);
});

</script>

<template>
    <div class="main-panel">
        <div v-show="showMode.value == 'request'">
            <PickListRequest :pickData="pickData" :showMode="showMode"/>
        </div>
        <div v-show="showMode.value == 'result'">
            <PickListResult :pickData="pickData" :showMode="showMode"/>
        </div>
    </div>

</template>

// client/NextJS/inv-mgmt/app/pages/components/PickList/PickList.tsx
'use_client'

import {useState, useEffect} from 'react';

import HttpService from '@/app/httpService';

import PickListRequest from "./PickListRequest";
import PickListResult from "./PickListResult";

export interface PickListProps {
  httpService?: HttpService;
}

export default function PickList({httpService}) {

  const [pickData,setPickData] = useState({
      available: null,
      unavailable: null
  });
  const [showMode,setShowMode] = useState('request');

  useEffect( () => {
    console.log("*** pick data useeffect " + pickData);
    if (pickData != null && pickData.available != null && pickData.unavailable != null) {
        console.log(pickData);
        // console.log("*** data has changed - avail " + pickData.available + "unavail " + pickData.unavailable);
        // setPickData({...pickData, available: pickData.available, unavailable:pickData.unavailable});
        setShowMode('result');
    }
 }, [pickData]);

  return (
    <div className="main-panel">
      <div hidden={showMode=='result'} >
        <PickListRequest httpService={httpService} setPickData={setPickData}/>
      </div>
      <div hidden={showMode=='request'} >
        <PickListResult pickData={pickData} setShowMode={setShowMode}/>
      </div>
    </div>
  )
}
