// client/NextJS/inv-mgmt/app/page.tsx
'use client'

import Script from 'next/script'

import { useState, useEffect, useRef } from 'react';

import AddVial from '@/app/pages/components/AddVial/AddVial';
import LocateVial from '@/app/pages/components/LocateVial/LocateVial';
import SearchInventory from '@/app/pages/components/SearchInventory/SearchInventory';
import PickList from '@/app/pages/components/PickList/PickList';

import HttpService from './httpService';

export default function Home() {
  let currentStatus = useRef("the default status value");
  const [status, setStatus] = useState(currentStatus.current);
  const [selectedPanel, setSelectedPanel] = useState("add vial");

  useEffect( () => {
    console.log("*** useEffect - " + status);
    if (status !== currentStatus.current) {
      console.log("*** status has changed!!!");
      currentStatus.current = status;
    }
 }, [status]);

 function showPanel(panelName:string) {
    setSelectedPanel(panelName);
  }

  const httpService = new HttpService();

  return (
    <main className="main-panel">
      <Script src="./scripts/plain-modal.min.js" 
        strategy="beforeInteractive"
        onLoad={()=>console.log("*** loaded")}
        onError={()=>console.log("*** ERROR")}
        onReady={()=>console.log("*** READY")}
      />
      <div className="content">
        <div id="button-panel">
          <button className="tabPanelButton" onClick={() => showPanel('add vial')}>Add New Vial</button>
          <button className="tabPanelButton" onClick={() => showPanel('search inventory')}>Search Inventory</button>
          <button className="tabPanelButton" onClick={() => showPanel('locate vial')}>Locate Vial</button>
          <button className="tabPanelButton" onClick={() => showPanel('pick list')}>Pick List</button>
        </div>
        <hr className="tabPanelBlank"/>
      </div>
      <div id="main-panel">
        <div hidden={selectedPanel != 'add vial'}>
          <AddVial httpService={httpService}/>
        </div>
        <div hidden={selectedPanel != 'search inventory'}>
          <SearchInventory httpService={httpService}/>
        </div>
        <div hidden={selectedPanel != 'locate vial'}>
          <LocateVial httpService={httpService}/>
        </div>
        <div hidden={selectedPanel != 'pick list'}>
          <PickList httpService={httpService}/>
        </div>
      </div>
    </main>
  );
}

// client/AngularJS/InvMgmt-material/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import {AddVial} from '../addVial/addVial';
import {SearchInventory} from '../searchInventory/searchInventory';
import {LocateVial} from '../locateVial/locateVial';
import {PickList} from '../pickList/pickList';

import {MatTabsModule} from '@angular/material/tabs';

// import *  as my_class from '/src/assets/scripts/my_class.js';
import * as logger  
    from "../scripts/logger" ;


@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, AddVial, SearchInventory, LocateVial, PickList, MatTabsModule],
  templateUrl: './app.component-material.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  title = 'Inventory Management';
  selected_panel = "add vial";
  hideMe = false;

  ngOnInit() {
    console.log("*** NG INIT");
    logger.print();
    let me = new logger.MyClass("bobby","da bear", 65);
    console.log(me.printMe());
  }
}


<style>
  
</style>

<main class="main">
  <div class="content">
    <div id="button-panel" style='text-align:center;'>
      <button class="tabPanelButton" (click)="showPanel('add vial')">Add New Vial</button>
      <button class="tabPanelButton" (click)="showPanel('search inventory')">Search Inventory</button>
      <button class="tabPanelButton" (click)="showPanel('locate vial')">Locate Vial</button>
      <button class="tabPanelButton" (click)="showPanel('pick list')">Pick List</button>
    </div>
    <hr class="tabPanelBlank"/>
    <div id="main-panel">
      <div [hidden]="selected_panel != 'add vial'">
        <add-vial></add-vial>
      </div>
      <div [hidden]="selected_panel != 'search inventory'">
        <search-inventory></search-inventory>
      </div>
      <div [hidden]="selected_panel != 'locate vial'">
        <locate-vial></locate-vial>
      </div>
      <div [hidden]="selected_panel != 'pick list'">
        <pick-list></pick-list>
      </div>
    </div>
  </div>
</main>


<router-outlet></router-outlet>
